name: LLM Code Review
description: A GitHub Action to automate code review using LLMs.
inputs:
  openai_api_key:
    description: 'OpenAI API key'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
