name: LLM Code Review
description: A GitHub Action to automate code review using LLMs.
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  anthropic_api_key:
    description: 'Anthropic API key'
    required: true
  llm_strategy:
    description: 'The LLM strategy to use'
    required: true
    default: 'anthropic'
  model:
    description: 'Name of the LLM to use'
    required: true
    default: 'claude-3-5-sonnet-20240620'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
    LLM_STRATEGY: ${{ inputs.llm_strategy }}
    MODEL: ${{ inputs.model }}
