name: LLM Code Review

on:
  issue_comment:
    types: [ created ]

jobs:
  review:
    if: github.event.issue.pull_request && github.event.comment.body == '/review-me'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
          fetch-depth: 0

      - name: Debug Workspace
        run: |
          echo "Contents of workspace:"
          ls -R
          echo "Current directory:"
          pwd

      - name: LLM Code Review
        uses: ./
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
