name: LLM Code Review

on:
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event.issue.pull_request && github.event.comment.body == '/review-me'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout PR
        run: |
          gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: LLM Code Review
        uses: your-username/your-action-repo@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
