name: LLM Code Review

on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    if: github.event.issue.pull_request && github.event.comment.body == '/review-me'
    runs-on: ubuntu-latest
    env:
      PERSONA: ${{ vars.PERSONA }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Post "Review in Progress" Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.issue.number }}
          body: 'Review in progress, it will be posted as soon as it is complete.'

      - name: LLM Code Review
        uses: ./
        with:
          github_token: ${{ github.token }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
